### PR TITLE
Implementation of Centroid Triplet Loss Function

### PR DESCRIPTION
**Pull request by Spinachboul**
## Hello Developers,
I have added the code for Centroid Triplet Loss function as an added implementation in the **"Loss"** folder.
I follows the basic code template, just contains a few changes in the forward function where the **The Centroid Triplet Loss** aims to learn embeddings (vectors) in such a way that distances between centroids belonging to the same group or cluster are minimized while distances between centroids of different groups are maximized.

### CODE REVIEW

**Review by Spinachboul — COMMENTED** [review]
Just the code indentation is slightly shifted , no change in the logic!

**Comment by HanClinto** [comment]
Looks like the build is failing due to formatting issues:

```
5:51:06 AM: /opt/buildhome/python3.8/lib/python3.8/site-packages/quaterion/loss/cos_face_loss.py:docstring of quaterion.loss.cos_face_loss.CosFaceLoss.forward:3: ERROR: Unexpected indentation.
5:51:06 AM: /opt/buildhome/python3.8/lib/python3.8/site-packages/quaterion/loss/cos_face_loss.py:docstring of quaterion.loss.cos_face_loss.CosFaceLoss.forward:4: WARNING: Block quote ends without a blank line; unexpected unindent.
5:51:06 AM: /opt/build/repo/docs/source/tutorials/triplet_loss_trick.rst:2: WARNING: Title underline too short.
5:51:06 AM: Triplet Loss: Vector Collapse Prevention
5:51:06 AM: ============================
```

**Comment by Spinachboul** [comment]
> Looks like the build is failing due to formatting issues:
> 
> ```
> 5:51:06 AM: /opt/buildhome/python3.8/lib/python3.8/site-packages/quaterion/loss/cos_face_loss.py:docstring of quaterion.loss.cos_face_loss.CosFaceLoss.forward:3: ERROR: Unexpected indentation.
> 5:51:06 AM: /opt/buildhome/python3.8/lib/python3.8/site-packages/quaterion/loss/cos_face_loss.py:docstring of quaterion.loss.cos_face_loss.CosFaceLoss.forward:4: WARNING: Block quote ends without a blank line; unexpected unindent.
> 5:51:06 AM: /opt/build/repo/docs/source/tutorials/triplet_loss_trick.rst:2: WARNING: Title underline too short.
> 5:51:06 AM: Triplet Loss: Vector Collapse Prevention
> 5:51:06 AM: ============================
> ```

**Comment by Spinachboul** [comment]
@HanClinto 
So should I again raise a PR for the function?

**Comment by HanClinto** [comment]
> @HanClinto So should I again raise a PR for the function?

I can't speak for the maintainers of Quaternion, but Centroid Triplet Loss looks like a very useful function to have -- I would personally be interested in trying it out!

**Comment by Spinachboul** [comment]
For now I have deleted the branch. I also thought of implementing n-pair which is apparently better than contrastive and triplet loss.

**Pull request closed without merging**
