### PR TITLE
Applying Center Loss

### PR DESCRIPTION
**Pull request by parthkl021**
This commit fixes the issue #187 
Center Loss as defined in the paper "A Discriminative Feature Learning Approach for Deep Face Recognition (http://ydwen.github.io/papers/WenECCV16.pdf) It aims to minimize the intra-class variations while keeping the features of different classes separable.

### CODE REVIEW

**Comment by parthkl021** [comment]
I am new to open source and this organization, can anyone give me an idea as for what are these issues and how should I solve them

**Comment by generall** [comment]
It failed because of documentation generation failed:

```
6:56:39 PM: /opt/buildhome/python3.8/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: "libc10_cuda.so: cannot open shared object file: No such file or directory"If you don"t plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
6:56:39 PM: /opt/build/repo/docs/source/api/index.rst:122: WARNING: autosummary: failed to import fastap_loss.FastAPLoss.
6:56:39 PM: Possible hints:
6:56:39 PM: * KeyError: "fastap_loss"
6:56:39 PM: * AttributeError: module "quaterion.loss" has no attribute "fastap_loss"
6:56:39 PM: * ModuleNotFoundError: No module named "quaterion.loss.fastap_loss"
6:56:39 PM: * ModuleNotFoundError: No module named "fastap_loss"
6:56:39 PM: /opt/build/repo/docs/source/getting_started/quick_start.rst:2: WARNING: Duplicate explicit target name: "tutorial".
6:56:39 PM: /opt/build/repo/docs/source/getting_started/quick_start.rst:2: WARNING: Duplicate explicit target name: "tutorial".
6:56:39 PM: /opt/build/repo/docs/source/getting_started/quick_start.rst:2: WARNING: Duplicate explicit target name: "tutorial".
6:56:39 PM: /opt/build/repo/docs/source/getting_started/quick_start.rst:2: WARNING: Duplicate explicit target name: "tutorial".
6:56:39 PM: /opt/buildhome/python3.8/lib/python3.8/site-packages/quaterion/loss/cos_face_loss.py:docstring of quaterion.loss.cos_face_loss.CosFaceLoss.forward:3: ERROR: Unexpected indentation.
6:56:39 PM: /opt/buildhome/python3.8/lib/python3.8/site-packages/quaterion/loss/cos_face_loss.py:docstring of quaterion.loss.cos_face_loss.CosFaceLoss.forward:4: WARNING: Block quote ends without a blank line; unexpected unindent.
6:56:39 PM: /opt/build/repo/docs/source/tutorials/triplet_loss_trick.rst:2: WARNING: Title underline too short.
6:56:39 PM: Triplet Loss: Vector Collapse Prevention
6:56:39 PM: ============================
6:56:39 PM: looking for now-outdated files... none found
6:56:39 PM: pickling environment... done
6:56:39 PM: checking consistency... done
6:56:39 PM: preparing documents... WARNING: unsupported theme option "social_preview" given
6:56:39 PM: done
6:56:39 PM: copying assets... copying static files... done
6:56:39 PM: copying extra files... done
6:56:39 PM: done
6:56:39 PM: writing output... [  1%] api/index
6:56:39 PM: Theme error:
6:56:39 PM: An error happened in rendering the page api/index.
6:56:39 PM: Reason: UndefinedError(""style" is undefined")
6:56:40 PM: ​
6:56:40 PM: "build.command" failed                                        
6:56:40 PM: ────────────────────────────────────────────────────────────────
6:56:40 PM: ​
6:56:40 PM:   Error message
6:56:40 PM:   Command failed with exit code 2: bash -x docs/generate_docs_netlify.sh (https://ntl.fyi/exit-code-2)
6:56:40 PM: ​
6:56:40 PM:   Error location
6:56:40 PM:   In build.command from netlify.toml:
6:56:40 PM:   bash -x docs/generate_docs_netlify.sh
6:56:40 PM: ​
6:56:40 PM:   Resolved config
6:56:40 PM:   build:
6:56:40 PM:     command: bash -x docs/generate_docs_netlify.sh
6:56:40 PM:     commandOrigin: config
6:56:40 PM:     environment:
6:56:40 PM:       - PYTHON_VERSION
6:56:40 PM:       - REVIEW_ID
6:56:40 PM:     publish: /opt/build/repo/docs/html
6:56:40 PM:     publishOrigin: config
6:56:41 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
6:56:41 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
6:56:41 PM: Failing build: Failed to build site
6:56:41 PM: Finished processing build request in 1m27.987s
```

**Comment by generall** [comment]
You can try to run locally `bash -x docs/generate_docs_netlify.sh`

**Comment by parthkl021** [comment]
The errors mentioned here are not of the files I made changes into, were they pre-existing or am I getting it wrong.
I just looked into the code its fast_ap_loss (in quaterion\loss__init__.py ) instead of fastap_loss as mentioned here

**Comment by parthkl021** [comment]
@generall I have added the changes

**Review by generall — APPROVED** [review]

**Pull request merged**
